project "tv_server"

    kind     "WindowedApp"
    language "C++"

    defines { "DEDICATED_ONLY", "TV_SERVER_ONLY", "TV_MODULE_HARD_LINKED" }
    flags   { "WinMain"}
    
    files   { 
        "*.h",
        "tv_module/*.h",
        "../gameshared/config.h",
        "../qcommon/bsp.h",
        "../qcommon/glob.h",
        "../gameshared/q_arch.h",
        "../gameshared/q_collision.h",
        "../gameshared/q_comref.h",
        "../gameshared/q_cvar.h",
        "../gameshared/q_dynvar.h",
        "../gameshared/q_math.h",
        "../gameshared/q_shared.h",
        "../gameshared/q_trie.h",
        "../qcommon/qcommon.h",
        "../qcommon/snap_read.h",
        "../qcommon/snap_write.h",
        "../qcommon/svnrev.h",
        "../qcommon/sys_fs.h",
        "../qcommon/sys_library.h",
        "../qcommon/sys_net.h",
        "../qcommon/version.h",
        "*.c",
        "tv_module/*.c",
        "../null/ascript_null.c",
        "../null/cl_null.c",
        "../qcommon/bsp.c",
        "../qcommon/cm_main.c",
        "../qcommon/cm_q3bsp.c",
        "../qcommon/cm_trace.c",
        "../qcommon/cmd.c",
        "../qcommon/common.c",
        "../win32/conproc.c",
        "../qcommon/cvar.c",
        "../qcommon/dynvar.c",
        "../qcommon/files.c",
        "../qcommon/glob.c",
        "../null/irc_null.c",
        "../qcommon/library.c",
        "../qcommon/md5.c",
        "../qcommon/mem.c",
        "../null/mm_null.c",
        "../qcommon/msg.c",
        "../qcommon/net.c",
        "../qcommon/net_chan.c",
        "../qcommon/patch.c",
        "../gameshared/q_math.c",
        "../gameshared/q_shared.c",
        "../qcommon/snap_demos.c",
        "../qcommon/snap_read.c",
        "../qcommon/snap_write.c",
        "../qcommon/svnrev.c",
        "../gameshared/q_trie.c",
        "../win32/win_fs.c",
        "../sdl/sdl_lib.c",
        "../win32/win_net.c",
        "../win32/win_sys.c",
        "../qcommon/wswcurl.c",
    }

    links {
        "libcurlstat",
        "zlibstat",
        "winmm",
        "ws2_32",
    }